updating yml file

diff --git a/.github/workflows/uchicago.yml b/.github/workflows/uchicago.yml
--- a/.github/workflows/uchicago.yml
+++ b/.github/workflows/uchicago.yml
@@ -22,6 +22,13 @@ jobs:
             sudo ln -s "$CANDIDATE" /usr/lib/x86_64-linux-gnu/libcrypt.so.2
           fi
           ls -l /usr/lib/x86_64-linux-gnu/libcrypt.so*
+      - name: Check PMG jobOptions on CVMFS
+        run: |
+          echo "MadGraphControl:"
+          ls /cvmfs/atlas.cern.ch/repo/sw/Generators/MCJobOptions/common/MadGraphControl || echo "MadGraphControl missing"
+          echo
+          echo "GeneratorFilters:"
+          ls /cvmfs/atlas.cern.ch/repo/sw/Generators/MCJobOptions/common/GeneratorFilters || echo "GeneratorFilters missing"
 
       - name: EVNT
         run: EVNT/UC/Native/run_evnt_native_batch.sh
